### PR TITLE
Automatic refresh of the session token

### LINKED ISSUE #7: After some time requests fail with an authentication error
The session token provided by the Freebox API has a limited lifetime, it needs to be refreshed from times to times otherwise the requests will end up failing when using a Freepybox instance for a long time.

### PR DESCRIPTION
**Pull request by stilllman**
This PR adds automatic refresh of the session token. The session token is requested when a request fails with an authentication error.

Should fix #7

### CODE REVIEW

**Comment by SNoof85** [comment]
As this is not working : 
What about refreshing session token on each call on get/put/post ? Too much ?

**Comment by stilllman** [comment]
I think this was not working because of a `raise_for_status` that I added to improve error reporting: this was preventing manual handling of failed requests, which is what we want to do here. I pushed a new commit to fix this, and to factorize the code that tries to refresh the session token.

**Comment by SNoof85** [comment]
I ended too on removing raise_for_status. I'll try with the new commit !

**Comment by stilllman** [comment]
The removal of `raise_for_status` should also fix #8 (and basically fix all the erroneous error reporting).

**Pull request merged**
